version: '3.8'
services:
  db:
    image: bitnami/mongodb:latest
    container_name: db
    ports:
      - "4002:27017"
    restart: always

  aws-storage:
    image: aws-storage
    build:
      context: .
      dockerfile: ./apps/aws-storage/Dockerfile.dev
    container_name: video-storage
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./apps/aws-storage:/usr/src/app/aws-storage:z
    ports:
      - "4001:80"
    env_file:
      - ./apps/aws-storage/.env.docker
    restart: "no"

  video-streaming:
    image: video-streaming:latest
    build:
      context: .
      dockerfile: ./apps/video-streaming/Dockerfile.dev
    container_name: video-streaming
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./apps/video-streaming:/usr/src/app/video-streaming:z
    ports:
      - "4000:80"
    env_file:
      - ./apps/video-streaming/.env.docker
    restart: "no"
