name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16.16.0"
        cache: "yarn"

    - name: Install Dependencies
      run: yarn install

    - name: Build Projects
      run: yarn build:all

  deploy:
    needs: build

    runs-on: ubuntu-latest
    env:
      ECR_TAG: ${{secrets.ECR_TAG}}
    steps:
    - name: Build images
      run: yarn deploy:all
